export interface RecipeTemplate {
  id: string;
  label: string;
  description: string;
  emoji: string;
  name: string;
  framework: string;
  language: string;
  styling: string;
  testing: string;
  allowedLibs: string;
  deniedLibs: string;
  aiRecommended?: boolean;
}

export const RECIPE_TEMPLATES: RecipeTemplate[] = [
  {
    id: "nextjs-enterprise",
    label: "Next.js Enterprise",
    description: "Full-stack React with SSR, Tailwind, and Vitest. Top LLM training coverage.",
    emoji: "N",
    name: "nextjs-enterprise",
    framework: "next.js",
    language: "typescript",
    styling: "tailwindcss",
    testing: "vitest",
    allowedLibs: "next, react, react-dom, tailwindcss, zod, drizzle-orm, zustand, @tanstack/react-query",
    deniedLibs: "moment, lodash, jquery, request",
    aiRecommended: true,
  },
  {
    id: "fastapi-service",
    label: "FastAPI Microservice",
    description: "High-performance Python API. Excellent AI code generation support.",
    emoji: "F",
    name: "fastapi-microservice",
    framework: "fastapi",
    language: "python",
    styling: "",
    testing: "pytest",
    allowedLibs: "fastapi, uvicorn, pydantic, sqlalchemy, alembic, httpx",
    deniedLibs: "flask, django",
    aiRecommended: true,
  },
  {
    id: "express-api",
    label: "Express API",
    description: "Node.js REST API. Simple patterns LLMs handle with high accuracy.",
    emoji: "E",
    name: "express-api",
    framework: "express",
    language: "typescript",
    styling: "",
    testing: "jest",
    allowedLibs: "express, zod, prisma, cors, helmet",
    deniedLibs: "jquery, request",
    aiRecommended: true,
  },
  {
    id: "django-rest",
    label: "Django REST API",
    description: "Batteries-included Python framework. Strong LLM pattern recognition.",
    emoji: "D",
    name: "django-rest-api",
    framework: "django",
    language: "python",
    styling: "",
    testing: "pytest",
    allowedLibs: "django, djangorestframework, celery, redis, psycopg2-binary",
    deniedLibs: "",
    aiRecommended: true,
  },
  {
    id: "flask-api",
    label: "Flask Lightweight API",
    description: "Minimal Python microframework. Clean patterns for AI-assisted dev.",
    emoji: "f",
    name: "flask-lightweight-api",
    framework: "flask",
    language: "python",
    styling: "",
    testing: "pytest",
    allowedLibs: "flask, flask-restx, marshmallow, SQLAlchemy, gunicorn",
    deniedLibs: "",
    aiRecommended: true,
  },
  {
    id: "react-spa",
    label: "React SPA",
    description: "Single-page React app with CSS Modules and Jest",
    emoji: "R",
    name: "react-spa",
    framework: "react",
    language: "typescript",
    styling: "css-modules",
    testing: "jest",
    allowedLibs: "react, react-dom, react-router-dom, zustand, axios",
    deniedLibs: "jquery, request",
    aiRecommended: true,
  },
  {
    id: "vue-dashboard",
    label: "Vue Dashboard",
    description: "Vue 3 + Tailwind for admin panels and dashboards",
    emoji: "V",
    name: "vue-dashboard",
    framework: "vue",
    language: "typescript",
    styling: "tailwindcss",
    testing: "vitest",
    allowedLibs: "vue, vue-router, pinia, vueuse",
    deniedLibs: "jquery, lodash",
  },
  {
    id: "spring-boot-api",
    label: "Spring Boot API",
    description: "Enterprise Java API with Spring ecosystem",
    emoji: "S",
    name: "spring-boot-api",
    framework: "spring-boot",
    language: "java",
    styling: "",
    testing: "junit",
    allowedLibs: "spring-boot-starter-web, spring-boot-starter-data-jpa, lombok, mapstruct",
    deniedLibs: "",
  },
  {
    id: "go-microservice",
    label: "Go Microservice",
    description: "Lightweight Go API with Gin and standard testing",
    emoji: "G",
    name: "go-microservice",
    framework: "gin",
    language: "go",
    styling: "",
    testing: "go-test",
    allowedLibs: "gin-gonic/gin, gorm, viper, zap",
    deniedLibs: "",
  },
  {
    id: "nestjs-api",
    label: "NestJS API",
    description: "Enterprise Node.js framework with decorators and DI",
    emoji: "N",
    name: "nestjs-api",
    framework: "nestjs",
    language: "typescript",
    styling: "",
    testing: "jest",
    allowedLibs: "@nestjs/core, @nestjs/common, @nestjs/typeorm, class-validator, class-transformer",
    deniedLibs: "express, jquery",
  },
  {
    id: "rails-monolith",
    label: "Rails Monolith",
    description: "Full-stack Ruby on Rails with RSpec testing",
    emoji: "R",
    name: "rails-monolith",
    framework: "rails",
    language: "ruby",
    styling: "",
    testing: "rspec",
    allowedLibs: "rails, devise, pundit, sidekiq, pg",
    deniedLibs: "",
  },
  {
    id: "astro-static",
    label: "Astro Static Site",
    description: "Content-first static site builder with island architecture",
    emoji: "A",
    name: "astro-static-site",
    framework: "astro",
    language: "typescript",
    styling: "tailwindcss",
    testing: "vitest",
    allowedLibs: "astro, @astrojs/react, @astrojs/tailwind, nanostores",
    deniedLibs: "jquery",
  },
  {
    id: "hono-edge",
    label: "Hono Edge API",
    description: "Ultra-fast edge runtime API for Cloudflare Workers / Deno",
    emoji: "H",
    name: "hono-edge-api",
    framework: "hono",
    language: "typescript",
    styling: "",
    testing: "vitest",
    allowedLibs: "hono, drizzle-orm, zod",
    deniedLibs: "express, fastify",
  },
  {
    id: "flutter-app",
    label: "Flutter Mobile",
    description: "Cross-platform mobile app with Dart",
    emoji: "F",
    name: "flutter-mobile-app",
    framework: "flutter",
    language: "dart",
    styling: "",
    testing: "",
    allowedLibs: "flutter, provider, dio, hive, go_router",
    deniedLibs: "",
  },
  {
    id: "aspnet-api",
    label: ".NET Web API",
    description: "C# API with ASP.NET Core and xUnit",
    emoji: ".",
    name: "aspnet-web-api",
    framework: "aspnet-core",
    language: "csharp",
    styling: "",
    testing: "xunit",
    allowedLibs: "MediatR, FluentValidation, AutoMapper, Serilog, EntityFrameworkCore",
    deniedLibs: "",
  },
];
